//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebViajes365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtractivoTuristico
    {
        public int idAtractivo { get; set; }
        public string tipoAtractivo { get; set; }
        public string Descripcion { get; set; }
        public int idLocalidad { get; set; }
    
        public virtual Localidades Localidades { get; set; }
    }
}
