//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebViajes365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int idChat { get; set; }
        public int idUsuario { get; set; }
        public string Consulta { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
