//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebViajes365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foro
    {
        public int idForo { get; set; }
        public string Procedencia { get; set; }
        public string MotivoVisita { get; set; }
        public string Conformidad { get; set; }
        public string Post { get; set; }
        public int idUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
