//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebViajes365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Itinerario()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int idItinerarios { get; set; }
        public string Rutas { get; set; }
        public string Transporte { get; set; }
        public string cantDpto { get; set; }
        public string tipoItinerario { get; set; }
        public string kmsRecorridos { get; set; }
        public string hsViaje { get; set; }
        public int idLocalidad { get; set; }
    
        public virtual Localidades Localidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
